### ISSUE TITLE
Sonar not able to connect to Postgres

### ISSUE THREAD

**Issue by theiamdude** [marcelbirkner/docker-ci-tool-stack#29] opened 2016-10-06 05:59 UTC
So I am setting this up for the second time. The first time it worked like a dream and that was about 4 months ago. it's a bit challenging to get it up and running. Here is the issue I am facing now:
When the Sonar container, it's not able to connect to SonarDB container. I initially had an issue with SonarDB starting as I was getting this error: 

> chmod: changing permissions of ‘/var/lib/postgresql/data’: Permission denied

I fixed the issue by updating the docker-compose.yml file by updating the volume mount section to the following (notice the :z at the end):

```
volumes:
    - /opt/postgres/data:/var/lib/postgresql/data:z
```

So now I am able to start the postgre container but I am still getting connectivity issue: 

> 2016.10.06 05:20:11 INFO  web[o.s.c.p.Database] Create JDBC datasource for jdbc:postgresql://sonardb:5432/sonar
> 2016.10.06 05:20:11 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
> java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').

I noticed then the docker-compose.yml file does not expose port 5432 on postgre container instead it doing so on the sonar container which did not make sense. I updated compose file to the following:

```
sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   #- "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
 sonardb:
  ports:
   - "5432:5432"
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data:z
```

Unfortunately I am still getting the connectivity issue from Sonar container. The only I am thinking about is that the DB is not created in postgres container and thus unable to connect. Should this step be done manually?

Here is the environment I am running this on:
OS: Fedora 24 
Docker:

```
[emc@cloud docker-ci-tool-stack]$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64
```

Docker Compose:

```
emc@cloud docker-ci-tool-stack]$ docker-compose version
docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j-fips  26 Sep 2016
```

Your help is greatly appreciated.
Cheers,
Mehdi

**Comment by theiamdude** [comment] 2016-10-06 06:53
One more finding. When I tail the postgres container logs I can see that when sonar container is starting, the following error appears:
`FATAL:  role "sonar" does not exist`

This is indicating that network connectivity is fine and the postgres DB is not setup for sonar. Is  that correct?

**Comment by ethiclab** [comment] 2016-10-06 07:43
Could you please indicate the url of the fork (and the correct branch) you are using? It can be easier for us to try to reproduce the problem.

Best,

Edu.

**Comment by theiamdude** [comment] 2016-10-10 00:31
Hi Edu,

this is the URL i have used to clone the project. https://github.com/marcelbirkner/docker-ci-tool-stack.git
I am assuming that's the master branch.

Cheers,
Mehdi

**Comment by marcelbirkner** [comment] 2016-12-09 12:56
Hi @theiamdude 

the Postgres username and password where missing from the docker-compose.yml environment variables. That should be fixed now.

**Closed by marcelbirkner** 2016-12-09 12:56 UTC

**Comment by joedayz** [comment] 2017-01-02 06:23
Hi, I followed the instructions today and get it error:

Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.20.0.5", user "sonar", database "sonar", SSL off
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:408) ~[postgresql-9.3-1102-jdbc41.jar:na]
